CREATE DATABASE SENAC;

USE SENAC;

CREATE TABLE PRODS 
(codigo NUMERIC (3) NOT NULL,
nome VARCHAR (50) NOT NULL,
preco NUMERIC(5,2) NOT NULL,
tipo CHAR(1) NULL ,
CONSTRAINT PK1 PRIMARY KEY ( codigo ));

INSERT INTO PRODS
VALUES (10 , "HDMI" , 100 , 'C' ) ;
INSERT INTO PRODS
VALUES (11 , "USB" , 100 , 'Z' ) ;
INSERT INTO PRODS
VALUES (12 , "HD" , 100 , 'D' ) ;
INSERT INTO PRODS
VALUES (13 , "HD" , 100 , 'C' ) ;
INSERT INTO PRODS
VALUES (14 , "USB" , 100 , 'D' ) ;
INSERT INTO PRODS
VALUES (15 , "HDMI" , 100 , 'Z' ) ;
INSERT INTO PRODS
VALUES (16 , "HDMI" , 100 , 'Z' ) ;

SELECT * FROM PRODS;

SELECT nome FROM PRODS;

SELECT tipo FROM PRODS;

SELECT tipo FROM PRODS WHERE tipo = "C";
SELECT tipo FROM PRODS WHERE tipo = "D";
SELECT tipo FROM PRODS WHERE tipo = "Z";

SELECT AVG(preco) AS mediatodos FROM PRODS;
SELECT AVG(preco) AS mediad FROM PRODS WHERE tipo = 'D'; 
SELECT AVG(preco) AS mediaprod FROM PRODS WHERE preco

